export enum Currency {
  US_DOLLAR = "USD", // United States Dollar
  EURO = "EUR", // Euro
  BRITISH_POUND = "GBP", // British Pound Sterling
  JAPANESE_YEN = "JPY", // Japanese Yen
  AUSTRALIAN_DOLLAR = "AUD", // Australian Dollar
  CANADIAN_DOLLAR = "CAD", // Canadian Dollar
  SWISS_FRANC = "CHF", // Swiss Franc
  CHINESE_YUAN = "CNY", // Chinese Yuan
  HONG_KONG_DOLLAR = "HKD", // Hong Kong Dollar
  NEW_ZEALAND_DOLLAR = "NZD", // New Zealand Dollar
  SWEDISH_KRONA = "SEK", // Swedish Krona
  SOUTH_KOREAN_WON = "KRW", // South Korean Won
  SINGAPORE_DOLLAR = "SGD", // Singapore Dollar
  NORWEGIAN_KRONE = "NOK", // Norwegian Krone
  MEXICAN_PESO = "MXN", // Mexican Peso
  INDIAN_RUPEE = "INR", // Indian Rupee
  RUSSIAN_RUBLE = "RUB", // Russian Ruble
  SOUTH_AFRICAN_RAND = "ZAR", // South African Rand
  TURKISH_LIRA = "TRY", // Turkish Lira
  BRAZILIAN_REAL = "BRL", // Brazilian Real
  NEW_TAIWAN_DOLLAR = "TWD", // New Taiwan Dollar
  DANISH_KRONE = "DKK", // Danish Krone
  POLISH_ZLOTY = "PLN", // Polish Złoty
  THAI_BAHT = "THB", // Thai Baht
  INDONESIAN_RUPIAH = "IDR", // Indonesian Rupiah
  HUNGARIAN_FORINT = "HUF", // Hungarian Forint
  CZECH_KORUNA = "CZK", // Czech Koruna
  ISRAELI_SHEKEL = "ILS", // Israeli New Shekel
  CHILEAN_PESO = "CLP", // Chilean Peso
  PHILIPPINE_PESO = "PHP", // Philippine Peso
  UAE_DIRHAM = "AED", // United Arab Emirates Dirham
  COLOMBIAN_PESO = "COP", // Colombian Peso
  SAUDI_RIYAL = "SAR", // Saudi Riyal
  MALAYSIAN_RINGGIT = "MYR", // Malaysian Ringgit
  ROMANIAN_LEU = "RON", // Romanian Leu
  NIGERIAN_NAIRA = "NGN", // Nigerian Naira
  BANGLADESHI_TAKA = "BDT", // Bangladeshi Taka
  PAKISTANI_RUPEE = "PKR", // Pakistani Rupee
  VIETNAMESE_DONG = "VND", // Vietnamese Dong
  EGYPTIAN_POUND = "EGP", // Egyptian Pound
  KENYAN_SHILLING = "KES", // Kenyan Shilling
  GHANAIAN_CEDI = "GHS", // Ghanaian Cedi
  TANZANIAN_SHILLING = "TZS", // Tanzanian Shilling
  UGANDAN_SHILLING = "UGX", // Ugandan Shilling
  ETHIOPIAN_BIRR = "ETB", // Ethiopian Birr
  CFA_FRANC_BEAC = "XAF", // Central African CFA Franc
  CFA_FRANC_BCEAO = "XOF", // West African CFA Franc
  MOROCCAN_DIRHAM = "MAD", // Moroccan Dirham
  ALGERIAN_DINAR = "DZD", // Algerian Dinar
  TUNISIAN_DINAR = "TND", // Tunisian Dinar
  QATARI_RIYAL = "QAR", // Qatari Riyal
  KUWAITI_DINAR = "KWD", // Kuwaiti Dinar
  BAHRAINI_DINAR = "BHD", // Bahraini Dinar
  OMANI_RIAL = "OMR", // Omani Rial
  ARGENTINE_PESO = "ARS", // Argentine Peso
  PERUVIAN_SOL = "PEN", // Peruvian Sol
  URUGUAYAN_PESO = "UYU", // Uruguayan Peso
  BOLIVIAN_BOLIVIANO = "BOB", // Bolivian Boliviano
  PARAGUAYAN_GUARANI = "PYG", // Paraguayan Guarani
  COSTA_RICAN_COLON = "CRC", // Costa Rican Colon
  DOMINICAN_PESO = "DOP", // Dominican Peso
  JAMAICAN_DOLLAR = "JMD", // Jamaican Dollar
  TRINIDAD_TOBAGO_DOLLAR = "TTD", // Trinidad and Tobago Dollar
  ICELANDIC_KRONA = "ISK", // Icelandic Króna
  CROATIAN_KUNA = "HRK", // Croatian Kuna
  SERBIAN_DINAR = "RSD", // Serbian Dinar
  BULGARIAN_LEV = "BGN", // Bulgarian Lev
  UKRAINIAN_HRYVNIA = "UAH", // Ukrainian Hryvnia
  GEORGIAN_LARI = "GEL", // Georgian Lari
  ARMENIAN_DRAM = "AMD", // Armenian Dram
  KAZAKHSTANI_TENGE = "KZT", // Kazakhstani Tenge
  UZBEKISTAN_SOM = "UZS", // Uzbekistan Som
  AZERBAIJANI_MANAT = "AZN", // Azerbaijani Manat
  SRI_LANKAN_RUPEE = "LKR", // Sri Lankan Rupee
  NEPALESE_RUPEE = "NPR", // Nepalese Rupee
  MYANMAR_KYAT = "MMK", // Myanmar Kyat
  CAMBODIAN_RIEL = "KHR", // Cambodian Riel
  LAO_KIP = "LAK", // Lao Kip
  FIJIAN_DOLLAR = "FJD", // Fijian Dollar
  PAPUA_NEW_GUINEAN_KINA = "PGK", // Papua New Guinean Kina
  SAMOAN_TALA = "WST", // Samoan Tala
  TONGAN_PAANGA = "TOP", // Tongan Paʻanga
  SOLOMON_ISLANDS_DOLLAR = "SBD", // Solomon Islands Dollar
}
